name: Auto Generate Weekly Novel
on:
  schedule:
    - cron: "0 9 * * 5"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install openai requests
      - name: Run generation script
        run: python scripts/generate_game.py
