name: Full Novel Game Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"  # 毎週金曜 朝9時（JST）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate structure
        run: python scripts/generate_structure.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate script
        run: python scripts/generate_game.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate voice
        run: python scripts/generate_voice.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate bgm
        run: python scripts/generate_bgm.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate images
        run: python scripts/generate_image.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit all generated data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add output/
          git commit -m "ゲーム素材自動生成完了" || echo "No changes to commit"
          git push origin HEAD:main
