name: Generate Structure

on:
  push:
    paths:
      - 'plans/*.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: 構造設計を生成
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_structure.py

      - name: 生成されたファイルをコミット
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add output/
          git commit -m '構造設計ファイルを自動生成' || echo "No changes to commit"
          git push origin HEAD:main
